import { Inter } from "next/font/google";
import "./globals.css";
import ShowButtonUp from "./components/ShowButtonUp";
import NavBar from "./sections/NavBar";
import Footer from "./sections/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Q-line",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${inter.className} min-h-screen bg-background antialiased`}>
                <div className="relative flex min-h-screen flex-col">
                    <NavBar />
                    <main className="flex-1">
                        {children}
                    </main>
                    <Footer />
                    <ShowButtonUp />
                </div>
            </body>
        </html>
    );
} 